[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  function = "ingredient-prerender"
  path = "/ingrediente/*"

[build.environment]
  NODE_VERSION = "18"

# Headers para optimización
[[headers]]
  for = "/ingrediente/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para sitemap
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/xml"